# Generated by Django 5.0.1 on 2025-02-09 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_image_alter_movie_rating 2'),
        ('movies', '0002_review'),
    ]

    operations = [
    ]
