# Generated by Django 5.1.5 on 2025-02-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_intended_audience_alter_movie_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='intended_audience',
            field=models.CharField(choices=[('G', 'G - General Audience'), ('PG', 'PG - Parental Guidance Suggested'), ('PG-13', 'PG-13 - Parents Strongly Cautioned'), ('R', 'R - Restricted'), ('NR', 'NR - Not Rated')], default='G', max_length=10),
        ),
    ]
