"""
Django settings for OurSite project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# from decouple import config



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-veu2jio+auxf&i+$u&u(emzd^q10t^f+p^r0z@c3h53uz_dfv%'
# SECRET_KEY = config('SECRET_KEY', default='unsafe-secret-key')
# DEBUG = config('DEBUG', default=True, cast=bool)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
#Final time
# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Gmail SMTP server
EMAIL_PORT = 587  # Use port 587 for secure connections (TLS)
EMAIL_USE_TLS = True  # Mandatory for Outlook and Gmail
EMAIL_HOST_USER = 'arkpianist3@gmail.com' # os.getenv('EMAIL_HOST_USER')  # Your Outlook email address
EMAIL_HOST_PASSWORD = 'ryzlfdgbscdejkfu' # os.getenv('EMAIL_HOST_PASSWORD')  # App password for Outlook
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER # os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)  # Default "from" email


# # Dynamic email configuration based on environment variables
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')  # Default to Gmail
# EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))  # Default to TLS (587)
# EMAIL_USE_TLS = bool(int(os.getenv('EMAIL_USE_TLS', 1)))  # Use TLS by default
# EMAIL_USE_SSL = bool(int(os.getenv('EMAIL_USE_SSL', 0)))  # Disabled by default
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # To be dynamically set
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # To be dynamically set
# DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'webmaster@localhost')  # From address
# #



# Email-related settings
# EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')  # Default to Gmail
# EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
# EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
# EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
# EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='your-email@example.com')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='password')
# THIS CODE ABOVE IS more recent BUT I DON't Think its what I want idk tho

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # 'django.core.mail.backends.smtp.EmailBackend'
# # 'django.core.mail.backends.console.EmailBackend'
# # Yo this actually printed it to the console!!!
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'arkpianist3@gmail.com'  # Replace with your email
# EMAIL_HOST_PASSWORD = 'GETGOOGLEPASSKEYTHINGWHYSODIFFICULT'  # Replace with your email password
# #It works when you add your actual email and passkey here, but thats not very useful or scalable


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'accounts',
    'movies'
    # 'django.contrib.auth.models' brakes the code as well
    # 'django.contrib.auth.models' brakes the code as well
    # 'accounts' brakes the code
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OurSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':
        # may have to add [BASE_DIR / 'templates'], back
        [os.path.join(BASE_DIR, 'OurSite/templates')],
        #[BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OurSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# THIS IS NOW ADDING Django Authentication for Step 8 from Chat
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# now run these 3 commands! in terminal obv
# python manage.py makemigrations
# python manage.py migrate
# python manage.py runserver
# python manage.py migrate
# python manage.py runserver
#
# Okay now after doing all of that, it turns out I have two accounts/ urls!
# I bet that is what I have to change in url really fast
# I hope this works








# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / 'OurSite/static',
]

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'